name: ecommerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5  
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  font_awesome_flutter: ^10.5.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/AF1.jpg
    - assets/nike_shoe.jpg
    - assets/adidas_shoe.jpg
    - assets/puma_shoe.jpg
    - assets/converse_shoe.jpg
    - assets/AF1_1.jpg
    - assets/AF1_2.jpg
    - assets/nike_shoe1.jpg
    - assets/nike_shoe2.jpg
    - assets/puma_shoe1.jpg
    - assets/puma_shoe2.jpg
    - assets/converse_shoe1.jpg
    - assets/converse_shoe2.jpg
    - assets/adidas_shoe1.jpg
    - assets/adidas_shoe2.jpg
