// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj5tI5LE8_4kTYR2Yg1CqowG1vxJnMwhw',
    appId: '1:525473371840:web:85a406deb4865abf60bf25',
    messagingSenderId: '525473371840',
    projectId: 'e-commerce-7d2ad',
    authDomain: 'e-commerce-7d2ad.firebaseapp.com',
    storageBucket: 'e-commerce-7d2ad.firebasestorage.app',
    measurementId: 'G-RG5PMRKDJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGASmmg9W5cTzwrPCgGPSL44x4WcIq4n0',
    appId: '1:525473371840:android:8e8e0a54565df01460bf25',
    messagingSenderId: '525473371840',
    projectId: 'e-commerce-7d2ad',
    storageBucket: 'e-commerce-7d2ad.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj5tI5LE8_4kTYR2Yg1CqowG1vxJnMwhw',
    appId: '1:525473371840:web:efea45d986352dca60bf25',
    messagingSenderId: '525473371840',
    projectId: 'e-commerce-7d2ad',
    authDomain: 'e-commerce-7d2ad.firebaseapp.com',
    storageBucket: 'e-commerce-7d2ad.firebasestorage.app',
    measurementId: 'G-DL4Z2THBKY',
  );
}
